const appleSupport = (
  sourceId,
  url,
  major,
  requiredNeedles,
) => ({
  sourceId,
  publisher: "Apple",
  publisherFamily: "Apple",
  canonicalUrl: url,
  fetchUrl: url,
  sourceClass: "firstPartyStableReleaseHistory",
  roles: ["stableReleaseBoundary"],
  major,
  requiredNeedles,
  supportNote:
    "First-party grouped iOS release history used only to bound stable releases. Silence on beta chronology is not negative evidence.",
});

const secondary = (
  sourceId,
  publisher,
  url,
  roles,
  requiredNeedles,
  supportNote,
) => ({
  sourceId,
  publisher,
  publisherFamily: publisher,
  canonicalUrl: url,
  fetchUrl: url,
  sourceClass: "contemporaneousSecondary",
  roles,
  requiredNeedles,
  supportNote,
});

export const sourceSpecs = [
  appleSupport(
    "apple-ios-8-release-history",
    "https://support.apple.com/en-us/102782",
    8,
    ["iOS 8.4.1"],
  ),
  appleSupport(
    "apple-ios-9-release-history",
    "https://support.apple.com/en-us/103834",
    9,
    ["iOS 9.0.1", "iOS 9.0.2", "iOS 9.3.1", "iOS 9.3.5"],
  ),
  appleSupport(
    "apple-ios-10-release-history",
    "https://support.apple.com/en-us/102990",
    10,
    ["iOS 10.3.1"],
  ),
  appleSupport(
    "apple-ios-11-release-history",
    "https://support.apple.com/en-us/102991",
    11,
    [
      "iOS 11.0.1",
      "iOS 11.0.2",
      "iOS 11.0.3",
      "iOS 11.1.1",
      "iOS 11.1.2",
      "iOS 11.2.1",
    ],
  ),
  appleSupport(
    "apple-ios-12-release-history",
    "https://support.apple.com/en-us/118387",
    12,
    ["iOS 12.0.1", "iOS 12.3.1", "iOS 12.4.1"],
  ),
  appleSupport(
    "apple-ios-13-release-history",
    "https://support.apple.com/en-us/118392",
    13,
    [
      "iOS 13.1.1",
      "iOS 13.1.2",
      "iOS 13.1.3",
      "iOS 13.3.1",
      "iOS 13.4.1",
      "iOS 13.5.1",
    ],
  ),
  appleSupport(
    "apple-ios-14-release-history",
    "https://support.apple.com/en-us/118390",
    14,
    ["iOS 14.0.1", "iOS 14.5.1", "iOS 14.7.1", "iOS 14.8"],
  ),
  appleSupport(
    "apple-ios-26-release-history",
    "https://support.apple.com/en-us/123075",
    26,
    ["iOS 26.0.1", "iOS 26.2.1"],
  ),
  secondary(
    "bgr-ios-13-3-1-pb1",
    "BGR",
    "https://www.bgr.com/tech/ios-13-3-1-public-beta-1-is-now-available-to-download/",
    [
      "exactVersion",
      "publicChannel",
      "publicOrdinal",
      "appearanceDate",
    ],
    ["iOS 13.3.1 public beta 1", "Dec. 18, 2019"],
    "Contemporary report explicitly naming iOS 13.3.1 Public Beta 1 and its public availability on December 18, 2019.",
  ),
  secondary(
    "cultofmac-ios-13-3-1-pb1",
    "Cult of Mac",
    "https://www.cultofmac.com/news/apple-drops-first-ios-13-3-1-public-beta",
    [
      "exactVersion",
      "publicChannel",
      "publicOrdinal",
      "appearanceDate",
    ],
    ["iOS 13.3.1 public beta 1", "December 18, 2019"],
    "Independent contemporary report explicitly naming the first iOS 13.3.1 public beta and same-day public availability.",
  ),
  secondary(
    "9to5mac-ios-13-3-1-pb2",
    "9to5Mac",
    "https://9to5mac.com/2020/01/14/apple-releasing-second-developer-beta-of-ios-13-3-1-today/",
    [
      "exactVersion",
      "publicChannel",
      "publicOrdinal",
      "appearanceDate",
    ],
    ["iOS 13.3.1", "second public beta versions", "Jan 14 2020"],
    "Contemporary report naming iOS 13.3.1 and stating that the second public beta versions were released that day.",
  ),
  secondary(
    "forbes-ios-13-3-1-pb2",
    "Forbes",
    "https://www.forbes.com/sites/anthonykarcz/2020/01/14/ios-1331-public-beta-2-is-finally-back-after-long-hiatus/",
    [
      "exactVersion",
      "publicChannel",
      "publicOrdinal",
      "appearanceDate",
    ],
    ["iOS 13.3.1 Public Beta 2", "Jan 14, 2020"],
    "Independent contemporary report explicitly naming iOS 13.3.1 Public Beta 2 and the January 14 date.",
  ),
  secondary(
    "9to5mac-ios-13-3-1-pb3",
    "9to5Mac",
    "https://9to5mac.com/2020/01/22/apple-releasing-third-developer-beta-of-ios-13-3-1-today/",
    [
      "exactVersion",
      "publicChannel",
      "publicOrdinal",
      "appearanceDate",
    ],
    ["iOS 13.3.1", "third public beta versions", "Jan 22 2020"],
    "Contemporary report naming iOS 13.3.1 and stating that the third public beta versions were released that day.",
  ),
  secondary(
    "kobonemi-ios-13-3-1-pb3",
    "Kobonemi",
    "https://www.kobonemi.com/entry/2020/01/23/iOS13.3.1%E3%81%A8iPadOS_13.3.1_Public_Beta3%E3%81%8C%E5%88%A9%E7%94%A8%E5%8F%AF%E8%83%BD%E3%81%AB",
    [
      "exactVersion",
      "publicChannel",
      "publicOrdinal",
      "japanCalendarDate",
    ],
    ["iOS 13.3.1", "Public beta 3", "2020-01-23"],
    "Independent contemporary Japanese report explicitly naming iOS 13.3.1 Public Beta 3. Its January 23 Japan date is consistent with the January 22 Pacific date established by 9to5Mac.",
  ),
  secondary(
    "macrumors-ios-8-4-1-developer-only",
    "MacRumors",
    "https://www.macrumors.com/2015/07/22/ios-9-beta-app-store-reviews-disabled/",
    ["negativeApplicability", "developerOnlyStatement"],
    ["iOS 8.4.1", "available only to developers"],
    "Contemporary statement that the then-current iOS 8.4.1 pre-release build was available only to developers.",
  ),
  secondary(
    "osxdaily-ios-8-4-1-beta2-developer",
    "OS X Daily",
    "https://osxdaily.com/2015/07/30/ios-8-4-1-beta-2-released/",
    ["negativeApplicability", "developerOnlySequence", "contrast"],
    [
      "iOS 8.4.1 Beta 2",
      "registered developer program",
      "iOS 9 betas are available for public beta users",
    ],
    "Contemporary Beta 2 report limited to registered developers and explicitly contrasting the iOS 9 public-beta program.",
  ),
  secondary(
    "idownloadblog-ios-8-4-1-final",
    "iDownloadBlog",
    "https://www.idownloadblog.com/2015/08/13/apple-releases-ios-8-4-1-to-the-public/",
    ["stableReleaseBoundary", "developerSequenceBoundary"],
    ["iOS 8.4.1", "beta 2", "released"],
    "Contemporary final-release boundary that describes the original and second beta without establishing a public label.",
  ),
  secondary(
    "heise-ios-8-4-1-beta2-ambiguous",
    "Heise",
    "https://www.heise.de/news/iOS-8-4-1-und-Mac-OS-X-10-10-5-als-Beta-2-erhaeltlich-2765975.html",
    ["conflict", "ambiguousPublicProgramWording"],
    ["iOS 8.4.1", "Beta 2", "Teilnehmer am Public-Beta-Programm"],
    "Retained because its combined iOS/macOS headline and public-program wording can be read more broadly than the article's product-specific distribution details.",
  ),
  secondary(
    "iculture-ios-8-4-1-beta2-ambiguous",
    "iCulture",
    "https://www.iculture.nl/nieuws/ios-8-4-1-beta-2-downloaden/",
    ["conflict", "ambiguousTesterWording"],
    ["iOS 8.4.1", "beta 2", "goedgekeurde testers"],
    "Retained because it mentions approved testers while directing readers to developer distribution, leaving the public-channel identity ambiguous.",
  ),
  secondary(
    "9to5mac-ios-14-8-no-beta",
    "9to5Mac",
    "https://9to5mac.com/2021/09/13/apple-releasing-ios-14-8-and-ipados-14-8-to-the-public-today/",
    ["negativeApplicability", "releasedWithoutBetaTesting"],
    ["iOS 14.8 was not beta tested"],
    "Direct contemporary statement that iOS 14.8 was not beta tested.",
  ),
  secondary(
    "idropnews-ios-14-8-no-beta",
    "iDrop News",
    "https://www.idropnews.com/news/psa-apple-updates-all-of-its-devices-to-swiftly-block-terrifying-spyware/167697/",
    ["negativeApplicability", "releasedWithoutBetaTesting"],
    ["iOS 14.8", "without a beta version"],
    "Independent contemporary report that iOS 14.8 arrived without a beta version.",
  ),
];
